Move @types/babel__generator to dependencies
This is because the module augmentation is included in the `.d.ts` file,
which means consumers will get the tsc error:

```
node_modules/koa-node-resolve/lib/koa-module-specifier-transform.d.ts:23:16 - error TS2665: Invalid module name in augmentation. Module '@babel/generator' resolves to an untyped module at '/Users/aomarks/git/tachometer/node_modules/@babel/generator/lib/index.js', which cannot be augmented.

23 declare module '@babel/generator' {
                  ~~~~~~~~~~~~~~~~~~
```